GemsAndMosaics:
  PaperItem:
    MosaicPaper:
      DarkKey: "阴钥"
      LightKey: "阳匙"
      Balance: "均衡"
    DecomposePaper: "分解符"
    PerforatedPaper: "打孔符"
    DismantlePaper: "拆卸符"
  Gems:
    Quality:
      - "劣质"
      - "优秀"
      - "史诗"
    Baseattribute:
      - "移动速度|+43%"
      - "攻击力|+4343-536"
BaseConfig:
  CheckStartLine: "=====花花镶嵌====="
  CheckSlotLore: "未打孔"
  CheckEndLine: "=====镶嵌结束====="
  DarkSlotLore: "阴槽位"
  LightSlotLore: "阳槽位"
  BalanceSlotLore: "均衡槽位"
Items:
  Item1:
    DisPlayName: "速度宝石 劣质 IX级"
    Id: 337
    Lore:
      - "[物品类型] 宝石"
      - "移动速度+60%"
      - "说明:这个宝石从天上来"